spring.application.name=PFE
spring.datasource.url=jdbc:mysql://localhost:3306/pfeDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8086
server.servlet.context-path=/pfe
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
file.upload-dir=uploads
# Increase max file size to 50MB (adjust as needed)
spring.servlet.multipart.max-file-size=50MB
# Increase max request size to 50MB (should be >= max-file-size)
spring.servlet.multipart.max-request-size=50MB
